import React from 'react';
import './EvaluationReportTemplate.css';

export default function EvaluationReportTemplate() {
  return (
    <div className="a4-report-container" id="a4-evaluation-report">
      {/* HEADER */}
      <div className="report-header">
        <div className="report-logo">
          <span style={{ color: '#d02b20', fontWeight: '900', fontSize: '20px' }}>Honeywell</span>
        </div>
        <div className="report-title-section">
          <h2>EVALUATION REPORT</h2>
          <p>Comprehensive Model Performance & System Evaluation</p>
        </div>
        <div className="report-meta">
          <div><span>Report Generated:</span> {new Date().toLocaleDateString()}</div>
          <div><span>Evaluation Period:</span> May 15, 2024 - May 15, 2024</div>
          <div><span>Generated By:</span> SOC Analyst</div>
        </div>
      </div>

      <div className="red-divider"></div>

      {/* OVERVIEW */}
      <div className="report-section">
        <h3 className="section-title">OVERVIEW</h3>
        <div className="overview-kpis">
          <div className="kpi-box text-center">
            <div className="kpi-circle">96.8%</div>
            <div className="kpi-lbl">Overall Performance Score</div>
          </div>
          <div className="kpi-box text-center">
            <div className="kpi-val">7,534,218</div>
            <div className="kpi-lbl">Total Events Evaluated</div>
          </div>
          <div className="kpi-box text-center">
            <div className="kpi-val">75,342</div>
            <div className="kpi-lbl">Anomalies Detected</div>
          </div>
          <div className="kpi-box text-center">
            <div className="kpi-val">74,800</div>
            <div className="kpi-lbl">True Positives (TP)</div>
          </div>
          <div className="kpi-box text-center">
            <div className="kpi-val">2,153</div>
            <div className="kpi-lbl">Confirmed Threats</div>
          </div>
          <div className="kpi-box text-center">
            <div className="kpi-val">1.32%</div>
            <div className="kpi-lbl">False Positive Rate (FPR)</div>
          </div>
        </div>
      </div>

      {/* 1. DETECTION PERFORMANCE */}
      <div className="report-section">
        <h3 className="section-title">1. DETECTION PERFORMANCE (Overall)</h3>
        <div className="report-grid-3">
          <div className="perf-table-container">
             <table className="perf-table">
               <tbody>
                 <tr><td>Accuracy</td><td className="bold">97.4%</td></tr>
                 <tr><td>Precision (PPV)</td><td className="bold">96.2%</td></tr>
                 <tr><td>Recall (TPR)</td><td className="bold">95.4%</td></tr>
                 <tr><td>F1 Score</td><td className="bold">95.8%</td></tr>
                 <tr><td>Specificity</td><td className="bold">98.7%</td></tr>
               </tbody>
             </table>
             <div className="matrix-grid" style={{marginTop: '10px'}}>
               <div className="m-cell m-header"></div>
               <div className="m-cell m-header">Pred Anomaly</div>
               <div className="m-cell m-header">Pred Normal</div>
               <div className="m-cell m-header">Act Anomaly</div>
               <div className="m-cell tp">TP: 74,800</div>
               <div className="m-cell fn">FN: 136</div>
               <div className="m-cell m-header">Act Normal</div>
               <div className="m-cell fp">FP: 1,235</div>
               <div className="m-cell tn">TN: 7M+</div>
             </div>
          </div>
          <div className="chart-placeholder">
            <div>
              <div style={{fontWeight: 'bold', marginBottom: '5px'}}>ROC Curve</div>
              <div style={{width: '100px', height: '60px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative', margin: '0 auto'}}>
                <svg width="100" height="60" style={{position: 'absolute', bottom: 0, left: 0}} viewBox="0 0 100 60">
                   <path d="M0,60 Q10,10 100,0" fill="none" stroke="#d02b20" strokeWidth="2"/>
                </svg>
              </div>
            </div>
          </div>
          <div className="chart-placeholder">
            <div>
              <div style={{fontWeight: 'bold', marginBottom: '5px'}}>Precision-Recall Curve</div>
              <div style={{width: '100px', height: '60px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative', margin: '0 auto'}}>
                <svg width="100" height="60" style={{position: 'absolute', bottom: 0, left: 0}} viewBox="0 0 100 60">
                   <path d="M0,0 Q90,5 100,60" fill="none" stroke="#0ea5e9" strokeWidth="2"/>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 2. ATTACK TYPE ANALYSIS */}
      <div className="report-section">
        <h3 className="section-title">2. ATTACK TYPE ANALYSIS</h3>
        <div className="report-grid-2">
          <table className="perf-table full-width">
            <thead>
              <tr>
                <th>Attack Type</th>
                <th>Precision</th>
                <th>Recall</th>
                <th>F1 Score</th>
                <th>Support</th>
              </tr>
            </thead>
            <tbody>
              <tr><td>Brute Force</td><td>98.2%</td><td>97.5%</td><td>97.8%</td><td>1,245</td></tr>
              <tr><td>Impossible Travel</td><td>95.1%</td><td>92.3%</td><td>93.7%</td><td>856</td></tr>
              <tr><td>Credential Stuffing</td><td>97.4%</td><td>96.8%</td><td>97.1%</td><td>3,412</td></tr>
              <tr><td>Lateral Movement</td><td>92.5%</td><td>89.4%</td><td>90.9%</td><td>234</td></tr>
            </tbody>
          </table>
          <div className="bar-chart-mock">
             <div style={{fontWeight: 'bold', marginBottom: '10px', textAlign: 'center'}}>F1 Score by Attack Type</div>
             <div className="bar-row"><span className="bar-lbl">Brute Force</span><div className="bar-track"><div className="bar-fill" style={{width: '97.8%'}}></div></div><span className="bar-val">97.8%</span></div>
             <div className="bar-row"><span className="bar-lbl">Impossible Travel</span><div className="bar-track"><div className="bar-fill" style={{width: '93.7%'}}></div></div><span className="bar-val">93.7%</span></div>
             <div className="bar-row"><span className="bar-lbl">Credential Stuffing</span><div className="bar-track"><div className="bar-fill" style={{width: '97.1%'}}></div></div><span className="bar-val">97.1%</span></div>
             <div className="bar-row"><span className="bar-lbl">Lateral Movement</span><div className="bar-track"><div className="bar-fill" style={{width: '90.9%'}}></div></div><span className="bar-val">90.9%</span></div>
          </div>
        </div>
      </div>

      {/* 3. FALSE POSITIVES ANALYSIS */}
      <div className="report-section">
        <h3 className="section-title">3. FALSE POSITIVES ANALYSIS (Top 1% Alert Output)</h3>
        <div className="report-grid-3">
          <div className="chart-placeholder">
             <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px'}}>Alert Distribution</div>
               <div style={{width: '60px', height: '60px', borderRadius: '50%', border: '8px solid #0ea5e9', borderTopColor: '#d02b20', margin: '0 auto'}}></div>
               <div style={{marginTop: '5px'}}>TP: 98.4% | FP: 1.6%</div>
             </div>
          </div>
          <div className="chart-placeholder">
             <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px'}}>FP Rate Trend (7 Days)</div>
               <div style={{width: '120px', height: '50px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative', margin: '0 auto'}}>
                 <svg width="120" height="50" style={{position: 'absolute', bottom: 0, left: 0}} viewBox="0 0 120 50">
                    <polyline points="0,40 20,45 40,30 60,35 80,20 100,25 120,10" fill="none" stroke="#0ea5e9" strokeWidth="2"/>
                 </svg>
               </div>
             </div>
          </div>
          <div className="chart-placeholder">
             <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px'}}>Alerts per Hour</div>
               <div style={{width: '120px', height: '50px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative', margin: '0 auto'}}>
                 <svg width="120" height="50" style={{position: 'absolute', bottom: 0, left: 0}} viewBox="0 0 120 50">
                    <polygon points="0,50 0,40 30,40 45,20 60,10 75,30 100,45 120,40 120,50" fill="rgba(14, 165, 233, 0.3)" />
                 </svg>
               </div>
             </div>
          </div>
        </div>
      </div>

      {/* ROW 4, 5, 6 */}
      <div className="report-grid-3">
        <div className="report-section">
          <h3 className="section-title">4. EXPLAINABILITY SUMMARY</h3>
          <table className="perf-table full-width">
            <tbody>
              <tr><td>Average Explanation Time</td><td className="bold">0.45 sec</td></tr>
              <tr><td>Explanation Confidence</td><td className="bold">96.2%</td></tr>
              <tr><td colSpan="2" style={{borderBottom: 'none'}}><b>Top Contributing Features:</b></td></tr>
              <tr><td colSpan="2" style={{paddingTop: 0}}>1. Login Frequency<br/>2. Resource Access Bytes<br/>3. Impossible Travel Distance</td></tr>
            </tbody>
          </table>
        </div>
        <div className="report-section">
          <h3 className="section-title">5. COLD-START PERFORMANCE</h3>
          <table className="perf-table full-width">
            <tbody>
              <tr><td>Entities in Cold-Start</td><td className="bold">142</td></tr>
              <tr><td>Avg. Profiling Time</td><td className="bold">4.2 days</td></tr>
              <tr><td>Cold-Start FPR</td><td className="bold">3.1%</td></tr>
              <tr><td>Detection Rate (New)</td><td className="bold">91.4%</td></tr>
            </tbody>
          </table>
        </div>
        <div className="report-section">
          <h3 className="section-title">6. CONCEPT DRIFT ANALYSIS</h3>
          <table className="perf-table full-width">
            <tbody>
              <tr><td>Current Global Drift</td><td className="bold">12%</td></tr>
              <tr><td>Models Retrained (30d)</td><td className="bold">2</td></tr>
              <tr><td>Status</td><td className="bold" style={{color: '#10b981'}}>STABLE</td></tr>
              <tr><td>Last Retrain</td><td className="bold">May 12, 2024</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* ROW 7, 8, 9 */}
      <div className="report-grid-3">
        <div className="report-section">
          <h3 className="section-title">7. BASELINE COMPARISON</h3>
          <table className="perf-table full-width">
            <tbody>
              <tr><td>Global Precision</td><td className="bold">94.2%</td></tr>
              <tr><td>Baseline Precision</td><td className="bold">96.2%</td></tr>
              <tr><td>F1 Improvement</td><td className="bold" style={{color: '#10b981'}}>+2.0%</td></tr>
            </tbody>
          </table>
        </div>
        <div className="report-section">
          <h3 className="section-title">8. SCALABILITY & PERF</h3>
          <table className="perf-table full-width">
            <tbody>
              <tr><td>Avg. Inference Time</td><td className="bold">152 ms</td></tr>
              <tr><td>Events / Sec</td><td className="bold">12.4k</td></tr>
              <tr><td>System Status</td><td className="bold" style={{color: '#10b981'}}>HEALTHY</td></tr>
            </tbody>
          </table>
        </div>
        <div className="report-section">
          <h3 className="section-title">9. ALERT SEVERITY</h3>
          <div className="chart-placeholder" style={{flexDirection: 'row', gap: '10px', height: 'auto', padding: '10px'}}>
             <div style={{width: '40px', height: '40px', borderRadius: '50%', border: '6px solid #f59e0b', borderTopColor: '#d02b20', borderLeftColor: '#10b981'}}></div>
             <div style={{textAlign: 'left', fontSize: '7px'}}>
               <div style={{color: '#d02b20', fontWeight: 'bold'}}>Critical: 15%</div>
               <div style={{color: '#f59e0b', fontWeight: 'bold'}}>High: 35%</div>
               <div style={{color: '#10b981', fontWeight: 'bold'}}>Medium: 50%</div>
             </div>
          </div>
        </div>
      </div>
      
      {/* 10. IMPORT EXPORT */}
      <div className="report-section" style={{marginBottom: 0}}>
         <h3 className="section-title">10. INTEGRATION METRICS</h3>
         <div style={{display: 'flex', gap: '20px', fontSize: '8px', color: '#555'}}>
           <div>Data Sources: Active (4)</div>
           <div>Webhook Endpoints: Active (2)</div>
           <div>API Uptime: 99.99%</div>
         </div>
      </div>

      {/* Footer */}
      <div className="report-footer">
        <p>Honeywell Behavioral Anomaly Detection Platform | Auto-Generated Document | Page 1 of 1</p>
      </div>

    </div>
  );
}
