import React from 'react';
import './UserActivityReportTemplate.css';

export default function UserActivityReportTemplate() {
  return (
    <div className="a4-report-container" id="a4-user-activity-report">
      {/* HEADER */}
      <div className="report-header">
        <div className="report-logo">
          <span style={{ color: '#d02b20', fontWeight: '900', fontSize: '20px' }}>Honeywell</span>
        </div>
        <div className="report-title-section">
          <h2>USER ACTIVITY REPORT</h2>
          <p>Comprehensive Overview of User Activities, Logins and Risk Analysis</p>
        </div>
        <div className="report-meta">
          <div><span>Report Generated:</span> {new Date().toLocaleDateString()}</div>
          <div><span>Evaluation Period:</span> Jul 17, 2026 - Jul 20, 2026</div>
          <div><span>Generated By:</span> SOC Analyst</div>
        </div>
      </div>

      <div className="red-divider"></div>

      {/* 1. EXECUTIVE SUMMARY */}
      <div className="report-section">
        <h3 className="section-title">1. EXECUTIVE SUMMARY</h3>
        <p className="section-desc">This report provides a comprehensive overview of user activities across the platform during the selected time period. It includes login statistics, behavior insights, role analysis, and anomaly summaries to help security analysts monitor and assess user risk levels.</p>
        
        <div className="exec-summary-grid">
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#0ea5e9'}}>👤</div>
            <div className="exec-info">
              <div className="exec-val">1,285</div>
              <div className="exec-lbl">Total Active Users</div>
              <div className="exec-trend green">↑ 12.4% vs last 7 days</div>
            </div>
          </div>
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#8b5cf6'}}>🔑</div>
            <div className="exec-info">
              <div className="exec-val">18,452</div>
              <div className="exec-lbl">Total Login Attempts</div>
              <div className="exec-trend green">↑ 4.2% vs last 7 days</div>
            </div>
          </div>
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#10b981'}}>✅</div>
            <div className="exec-info">
              <div className="exec-val">16,782</div>
              <div className="exec-lbl">Successful Logins</div>
              <div className="exec-trend green">↑ 10.5% vs last 7 days</div>
            </div>
          </div>
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#ef4444'}}>❌</div>
            <div className="exec-info">
              <div className="exec-val">1,670</div>
              <div className="exec-lbl">Failed Login Attempts</div>
              <div className="exec-trend red">↑ 5.6% vs last 7 days</div>
            </div>
          </div>
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#f59e0b'}}>🌐</div>
            <div className="exec-info">
              <div className="exec-val">3,246</div>
              <div className="exec-lbl">Unique IP Addresses</div>
              <div className="exec-trend green">↑ 8.5% vs last 7 days</div>
            </div>
          </div>
          <div className="exec-kpi">
            <div className="exec-icon" style={{color: '#ef4444'}}>🛡️</div>
            <div className="exec-info">
              <div className="exec-val">42</div>
              <div className="exec-lbl">High Risk Users</div>
              <div className="exec-trend red">↑ 44.7% vs last 7 days</div>
            </div>
          </div>
        </div>
      </div>

      {/* 2. LOGIN OVERVIEW */}
      <div className="report-section">
        <h3 className="section-title">2. LOGIN OVERVIEW</h3>
        <div className="report-grid-2">
          <div className="table-wrapper">
             <table className="perf-table">
               <thead>
                 <tr><th>Metric</th><th>This Period</th><th>Last 7 Days</th><th>Change (%)</th></tr>
               </thead>
               <tbody>
                 <tr><td>Total Login Attempts</td><td className="bold">18,452</td><td>17,622</td><td className="green">↑ 4.20%</td></tr>
                 <tr><td>Successful Logins</td><td className="bold">16,782</td><td>15,229</td><td className="green">↑ 10.12%</td></tr>
                 <tr><td>Failed Login Attempts</td><td className="bold">1,670</td><td>1,584</td><td className="red">↑ 5.61%</td></tr>
                 <tr><td>Success Rate</td><td className="bold">90.95%</td><td>86.64%</td><td className="green">↑ 4.31%</td></tr>
                 <tr><td>Average Attempts per User</td><td className="bold">14.36</td><td>13.71</td><td className="green">↑ 4.74%</td></tr>
                 <tr><td>Unique Users Logged In</td><td className="bold">1,285</td><td>1,142</td><td className="green">↑ 12.40%</td></tr>
               </tbody>
             </table>
          </div>
          <div className="chart-placeholder">
             <div style={{width: '100%', padding: '0 10px'}}>
               <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '9px', textAlign: 'left'}}>Login Attempts Trend</div>
               <div style={{width: '100%', height: '80px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative'}}>
                 <svg width="100%" height="100%" viewBox="0 0 200 80" preserveAspectRatio="none">
                    <polyline points="0,50 40,45 80,30 120,40 160,20 200,30" fill="none" stroke="#0ea5e9" strokeWidth="2"/>
                    <polyline points="0,70 40,65 80,68 120,72 160,65 200,68" fill="none" stroke="#ef4444" strokeWidth="2"/>
                 </svg>
               </div>
             </div>
          </div>
        </div>
      </div>

      {/* 3. ACTIVITIES BY TIME */}
      <div className="report-section">
        <h3 className="section-title">3. ACTIVITIES BY TIME</h3>
        <div className="report-grid-3">
          <div className="chart-placeholder">
            <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px'}}>By Time of Day (Heatmap)</div>
               <div style={{display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '1px', width: '120px', height: '60px', margin: '0 auto'}}>
                 {Array.from({length: 24}).map((_, i) => (
                   <div key={i} style={{background: `rgba(14, 165, 233, ${Math.random()})`}}></div>
                 ))}
               </div>
            </div>
          </div>
          <div className="chart-placeholder">
             <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px'}}>By Day of Week</div>
               <div style={{display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', width: '120px', height: '60px', borderBottom: '1px solid #999', margin: '0 auto', padding: '0 5px'}}>
                 {['M','T','W','T','F','S','S'].map((day, i) => (
                   <div key={i} style={{width: '10px', height: `${20 + Math.random() * 40}px`, background: '#3b82f6'}}></div>
                 ))}
               </div>
             </div>
          </div>
          <div className="chart-placeholder">
             <div>
               <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px'}}>By Location (Top Countries)</div>
               <div style={{width: '60px', height: '60px', borderRadius: '50%', border: '12px solid #3b82f6', borderTopColor: '#f59e0b', borderRightColor: '#10b981', borderBottomColor: '#ef4444', margin: '0 auto'}}></div>
             </div>
          </div>
        </div>
      </div>

      {/* 4. ACTIVITY BY USER ROLES */}
      <div className="report-section">
        <h3 className="section-title">4. ACTIVITY BY USER ROLES</h3>
        <div className="report-grid-2" style={{gridTemplateColumns: '3fr 2fr'}}>
          <table className="perf-table full-width">
            <thead>
              <tr><th>Role</th><th>Total Users</th><th>Active Users</th><th>Login Attempts</th><th>Success Rate</th></tr>
            </thead>
            <tbody>
              <tr><td>SOC Analyst</td><td>245</td><td>221</td><td>5,124</td><td>98.50%</td></tr>
              <tr><td>IT Administrator</td><td>124</td><td>115</td><td>4,320</td><td>99.12%</td></tr>
              <tr><td>Security Engineer</td><td>354</td><td>310</td><td>3,850</td><td>97.80%</td></tr>
              <tr><td>System Administrator</td><td>156</td><td>142</td><td>2,800</td><td>98.15%</td></tr>
              <tr><td>Developer</td><td>340</td><td>301</td><td>1,540</td><td>94.50%</td></tr>
              <tr><td>Manager</td><td>145</td><td>120</td><td>1,420</td><td>95.20%</td></tr>
              <tr><td>Auditor</td><td>50</td><td>42</td><td>230</td><td>99.00%</td></tr>
              <tr><td>Others</td><td>24</td><td>18</td><td>62</td><td>92.50%</td></tr>
            </tbody>
          </table>
          <div className="chart-placeholder" style={{flexDirection: 'column'}}>
            <div style={{fontWeight: 'bold', marginBottom: '10px', fontSize: '9px'}}>Role-wise Activity Distribution</div>
            <div style={{width: '80px', height: '80px', borderRadius: '50%', border: '15px solid #0ea5e9', borderTopColor: '#f59e0b', borderRightColor: '#8b5cf6', borderBottomColor: '#10b981', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
               <span style={{fontSize: '8px', fontWeight: 'bold'}}>18,452</span>
            </div>
          </div>
        </div>
      </div>

      {/* 5. RISK LEVEL SUMMARY */}
      <div className="report-section">
        <h3 className="section-title">5. RISK LEVEL SUMMARY</h3>
        <div className="report-grid-3">
          <div className="chart-placeholder" style={{flexDirection: 'column'}}>
             <div style={{fontWeight: 'bold', marginBottom: '10px', fontSize: '9px'}}>Users by Risk Level</div>
             <div style={{display: 'flex', alignItems: 'center', gap: '15px'}}>
               <div style={{width: '50px', height: '50px', borderRadius: '50%', border: '8px solid #10b981', borderTopColor: '#f59e0b', borderRightColor: '#ef4444'}}></div>
               <div style={{fontSize: '7px', textAlign: 'left'}}>
                 <div><span style={{color: '#10b981'}}>●</span> Low: 85%</div>
                 <div><span style={{color: '#f59e0b'}}>●</span> Med: 12%</div>
                 <div><span style={{color: '#f97316'}}>●</span> High: 2%</div>
                 <div><span style={{color: '#ef4444'}}>●</span> Crit: 1%</div>
               </div>
             </div>
          </div>
          <div className="chart-placeholder" style={{flexDirection: 'column'}}>
             <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '9px', width: '100%', textAlign: 'left'}}>Risk Level Trend (7 Days)</div>
             <div style={{width: '100%', height: '60px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative'}}>
                <svg width="100%" height="100%" viewBox="0 0 100 60" preserveAspectRatio="none">
                   <polygon points="0,60 0,50 30,45 60,40 100,50 100,60" fill="rgba(16, 185, 129, 0.3)" />
                   <polygon points="0,50 0,30 30,25 60,35 100,30 100,50" fill="rgba(245, 158, 11, 0.3)" />
                   <polygon points="0,30 0,20 30,10 60,25 100,15 100,30" fill="rgba(239, 68, 68, 0.3)" />
                </svg>
             </div>
          </div>
          <div className="table-wrapper">
             <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px', padding: '5px'}}>Top Risky Users</div>
             <table className="perf-table full-width" style={{fontSize: '7px'}}>
               <thead><tr><th>User ID</th><th>Risk Level</th><th>Risk Score</th></tr></thead>
               <tbody>
                 <tr><td>usr_admin</td><td className="red bold">Critical</td><td>98</td></tr>
                 <tr><td>usr_1294</td><td className="red bold">Critical</td><td>92</td></tr>
                 <tr><td>usr_8872</td><td style={{color: '#f97316', fontWeight: 'bold'}}>High</td><td>85</td></tr>
                 <tr><td>usr_2214</td><td style={{color: '#f97316', fontWeight: 'bold'}}>High</td><td>79</td></tr>
               </tbody>
             </table>
          </div>
        </div>
      </div>

      {/* 6. TOP USERS BY ACTIVITY */}
      <div className="report-section">
        <h3 className="section-title">6. TOP USERS BY ACTIVITY</h3>
        <table className="perf-table full-width" style={{fontSize: '7px'}}>
          <thead>
            <tr><th>Rank</th><th>User</th><th>Department</th><th>Role</th><th>Total Logins</th><th>Success</th><th>Failed</th><th>Unique IPs</th><th>Last Login Time</th><th>Risk Score</th><th>Risk Level</th></tr>
          </thead>
          <tbody>
            {[
              {u: 'Abhay Sharma', d: 'Security Ops', r: 'SOC Analyst', l: 342, s: 338, f: 4, ip: 2, t: 'May 15, 08:14 AM', rs: 24, rl: 'Low', c: '#10b981'},
              {u: 'Rahul Patel', d: 'IT Operations', r: 'IT Engineer', l: 284, s: 281, f: 3, ip: 1, t: 'May 15, 09:22 AM', rs: 15, rl: 'Low', c: '#10b981'},
              {u: 'Priya Singh', d: 'Finance', r: 'Manager', l: 215, s: 215, f: 0, ip: 1, t: 'May 15, 10:05 AM', rs: 12, rl: 'Low', c: '#10b981'},
              {u: 'Sanjay Reddy', d: 'Security Ops', r: 'Security Engineer', l: 198, s: 189, f: 9, ip: 4, t: 'May 15, 07:30 AM', rs: 82, rl: 'High', c: '#f97316'},
              {u: 'Meera Mohan', d: 'HR', r: 'HR Executive', l: 182, s: 182, f: 0, ip: 1, t: 'May 15, 09:45 AM', rs: 18, rl: 'Low', c: '#10b981'},
              {u: 'Amit Gupta', d: 'IT Operations', r: 'System Admin', l: 165, s: 161, f: 4, ip: 2, t: 'May 15, 11:12 AM', rs: 22, rl: 'Low', c: '#10b981'},
              {u: 'Neha Bansal', d: 'Sales', r: 'Sales Rep', l: 154, s: 148, f: 6, ip: 3, t: 'May 15, 08:50 AM', rs: 45, rl: 'Medium', c: '#f59e0b'},
              {u: 'Vikram Singh', d: 'Engineering', r: 'Developer', l: 142, s: 140, f: 2, ip: 1, t: 'May 15, 09:10 AM', rs: 14, rl: 'Low', c: '#10b981'},
              {u: 'Deepak Singh', d: 'Engineering', r: 'Lead Engineer', l: 131, s: 129, f: 2, ip: 1, t: 'May 15, 10:30 AM', rs: 16, rl: 'Low', c: '#10b981'},
              {u: 'Sweta Reddy', d: 'Marketing', r: 'Manager', l: 128, s: 125, f: 3, ip: 2, t: 'May 15, 09:00 AM', rs: 32, rl: 'Medium', c: '#f59e0b'}
            ].map((row, i) => (
              <tr key={i}>
                <td>{i+1}</td><td>{row.u}</td><td>{row.d}</td><td>{row.r}</td><td>{row.l}</td><td>{row.s}</td><td>{row.f}</td><td>{row.ip}</td><td>{row.t}</td><td>{row.rs}</td><td style={{color: row.c, fontWeight: 'bold'}}>{row.rl}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 7. ANOMALOUS ACTIVITY SUMMARY */}
      <div className="report-section">
        <h3 className="section-title">7. ANOMALOUS ACTIVITY SUMMARY</h3>
        <div className="report-grid-3">
          <table className="perf-table full-width">
            <thead><tr><th>Anomalous Activities Detected</th><th>Count</th></tr></thead>
            <tbody>
              <tr><td>Impossible Travel Detected</td><td className="bold">18</td></tr>
              <tr><td>Brute Force Attempts</td><td className="bold">42</td></tr>
              <tr><td>Multiple Failed Logins</td><td className="bold">86</td></tr>
              <tr><td>Unusual Access Time</td><td className="bold">21</td></tr>
              <tr><td>Privilege Escalation</td><td className="bold">4</td></tr>
              <tr><td className="bold">Total Anomalous Events</td><td className="bold">171</td></tr>
            </tbody>
          </table>
          <div className="chart-placeholder" style={{flexDirection: 'column', alignItems: 'flex-start', padding: '10px'}}>
             <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px'}}>Anomalous Activities Over Time</div>
             <div style={{width: '100%', height: '60px', borderLeft: '1px solid #999', borderBottom: '1px solid #999', position: 'relative'}}>
                <svg width="100%" height="100%" viewBox="0 0 100 60" preserveAspectRatio="none">
                   <polyline points="0,50 20,45 40,20 60,35 80,10 100,25" fill="none" stroke="#ef4444" strokeWidth="2"/>
                </svg>
             </div>
          </div>
          <div className="chart-placeholder" style={{flexDirection: 'column', alignItems: 'flex-start', padding: '10px'}}>
             <div style={{fontWeight: 'bold', marginBottom: '5px', fontSize: '8px'}}>Top Departments with Anomalies</div>
             <div style={{width: '100%'}}>
                {['IT Operations', 'Security Operations', 'Finance', 'Engineering'].map((d, i) => (
                  <div key={i} style={{display: 'flex', alignItems: 'center', gap: '5px', marginBottom: '3px', fontSize: '6px'}}>
                    <div style={{width: '40px'}}>{d}</div>
                    <div style={{flex: 1, height: '6px', background: '#e5e7eb'}}>
                       <div style={{width: `${100 - i * 20}%`, height: '100%', background: '#3b82f6'}}></div>
                    </div>
                  </div>
                ))}
             </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="report-footer" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderTop: '1px solid #ddd', paddingTop: '10px'}}>
        <div style={{textAlign: 'left'}}>
          <strong>Notes:</strong><br/>
          • All times are shown in UTC+05:30 Asia/Kolkata<br/>
          • Data is refreshed every 5 minutes<br/>
          • This report is auto-generated. For detailed investigation, please refer to the platform.
        </div>
        <div style={{textAlign: 'right'}}>
          <div><strong>Report Generated By:</strong></div>
          <div>SOC Analyst</div>
          <div style={{marginTop: '5px', fontFamily: 'cursive', fontSize: '12px', color: '#111'}}>SOC Analyst</div>
        </div>
      </div>

    </div>
  );
}
